---
<% require File.expand_path(File.join(__FILE__, '..', 'support', 'env')) %>
driver:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  require_chef_omnibus: "11.4.4"
provisioner:
  name: chef_zero
  attributes: { kitchen: true }
platforms:
  - name: amazon-2014.10
    driver_plugin: ec2
    driver_config:
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
      username: ec2-user
      image_id: ami-0e289766
      region: us-east-1
      availability_zone: us-east-1b
      security_group_ids: ['ci-testing']
      interface: public
      tags:
        Name: <%= "##{ENV['CI'] ? 'travis-ci' : ENV['USER']}-opsworks-bashrc-kitchen" %>
        Env: public
suites:
  - name: default
    run_list:
      - recipe[opsworks-bashrc::default]
    attributes:
      opsworks:
        instance:
          private_ip: '1.2.3.4'
          hostname: 'foo_app_01'
          instance_type: 't1.micro'
          aws_instance_id: 'asdfjkl'
          availability_zone: 'us-east'
        applications:
          - slug_name: 'foo_app'
